- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 7ec485352199e02d608198b0206b0675fa84af73
  hooks:
  - id: trailing-whitespace
    files: \.(py|sh|yaml|txt)$
  - id: flake8
    files: \.py$
  - id: debug-statements
    files: \.py$
